### ISSUE TITLE
openHAB 2

### ISSUE THREAD

**Issue by YourhighnessLeender** [paphko/mmm-openhabfloorplan#1]
Has anyone been successful in making this work on openHab2? I'm trying, but cen't seem to get my devices to get any startuses

**Comment by paphko** [comment]
AFAIK the REST API of openHAB does not have any breaking changes from version 1 to 2, so I thought that it should work. But I didn't test it yet, my plan is to migrate to OH2 in February...

If you have any error in your log, post it here and I'll see whether I can fix it.

**Comment by paphko** [comment]
I just found out why OH2 is not working, the REST API does *not* behave the same way: when making a GET request in OH1, a parameter 'type=json' is required to get a json response; in OH2 json is the default format and the 'type=json' parameter does not return anything. Unfortunately.

The easiest fix that comes into my mind right now is to add an explicit option in config.js to set the openhab version and check that option in buildRequestParams of node_helper.js.

**Comment by YourhighnessLeender** [comment]
@paphko thank you for taking the time to look at it. Do you think that there is any possibility that you might guide me if there is anything I can to to get it working? If not I'll await the updated code.

Much appreciated - great module!

**Comment by paphko** [comment]
Please try as follows:

1. in mmm-openhabfloorplan.js add option 'version' in 'openhab' section with default value = 2
  (since OH2 is now officially released, it should  be the default version)
2. in node_helper.js replace line 51 with:
  `url += "rest/items" + (openhab.version === 1 ? "?type=json" : "");`

Please tell me if that works.

**Comment by YourhighnessLeender** [comment]
![img_4922](https://cloud.githubusercontent.com/assets/22977108/22253585/73072156-e252-11e6-92d2-13081420f1ab.JPG)

At least got the floor plan up and running. :-)

**Comment by YourhighnessLeender** [comment]
I've followed your instructions, but with no luck. But as I said, I might be doing something wrong.

Here is my config:
`{
                        module: 'mmm-openhabfloorplan',
                        position: 'middle_center',
                        config: {
                                draft: false,
                                updateInterval: 10*60*1000,
                                openhab: {
                                        url: "http://192.168.1.224:8080/",
                                        },
                                floorplan: {
                                        image: "floorplan.png",
                                        width: 507,
                                        height: 478,
                                        },
                                lights: {
                                        tellstick_switch_8f59842e_1299953_state: { left: 134,  top: 30 },
                                        tellstick_switch_8f59842e_1299926_state: { left: 265,  top: 40 },
                                        samsungtv_tv_0d1cef01_00dc_1000_9f61_f47b5ebe4871_power: { left: 180,  top: 25 }
                                        }
                        }
                },
`

node_helper.js:
` buildRequestParams: function(openhab) {
                // build url of openhab server to get status of group items in json format
                var url = openhab.url;
                if (!url.endsWith('/'))
                        url += '/';
                url += "rest/items" + (openhab.version === 1 ? "?type=json" : "");
`

Defaults in mmm-openhabfloorplan.js:
 `defaults: {
                /* with the openhab http binding, all changes can directly be pushed to the mirror. */
                /* please see documentation of this module how this works. */
                updateInterval: 60 * 60 * 1000, // refreshing all windows / lights / labels once per hour; 0 to disable periodic update
                draft: false, // if true, all lights and windows and the label names are shown; if false, get states from openhab
                openhab: {
                        url: "http://openhab:8080", // must not have trailing slash!
                        user: "",
                        password: "",
                        version: 2
                },`

**Comment by paphko** [comment]
The config looks good. What does the log say? If communication with openhab server fails, there should be something in the log file.

Update: try removing the trailing slash in your config.js!

**Comment by YourhighnessLeender** [comment]
Thanks for feedback, removed the slash, but no luck.
Where do I find the logs? There is no npm-debug.log in the MM directory

**Comment by paphko** [comment]
-> https://forum.magicmirror.builders/topic/198/flushing-pm2-logs

**Comment by paphko** [comment]
OH 1 and 2 provide different JSON format in items respons via REST API. This should be fixed now. Please pull latest changes and try again.

**Comment by JahFyahh** [comment]
Has anyone got this working? It does not seem to work for me.
Using the get rule does not work either.

**Comment by paphko** [comment]
I recently updated zo OH2 and it works fine.
