### ISSUE TITLE
Rule ERROR "Illegal character in query"

### ISSUE THREAD

**Issue by rbrueckner82** [paphko/mmm-openhabfloorplan#10]
Hello,

I get the following error in the openhab log

`Rule 'send updates to MagicMirror': Illegal character in query at index 77: http://192.168.**.***:8080/openhab?item=ZbtempBedroom_Temperature&state=16.93 °C` 

My Rule

`// define your magic mirror URL here; make sure that there is no trailing slash
var String mirrorUrl = "http://192.168.**.***:8080/openhab"

rule "send updates to MagicMirror"

when
	Member of gzb_magicmirror changed
then
		var url = ( mirrorUrl + "?item=" + triggeringItem.name + "&state=" + triggeringItem.state )
		sendHttpGetRequest(url)
		logInfo("MagicMirror","Sent to MM: "+ url)
end`

I think it's the special character "°C" or the Space but encodeURI (*) does not work.

Any ideas? Thanks

**Comment by paphko** [comment]
At the moment, I cannot test it, but you could try this snippet to convert your state value to a string for the request:

String::valueOf(triggeringItem.state).replaceAll("°", " ")

It is also null-safe, this is why I suggest String.valueOf.

If spaces are also not working, you could try: replaceAll("[° ]", "_")
