### ISSUE TITLE
Rule doesn't work in OH3

### ISSUE THREAD

**Issue by BenCanada** [paphko/mmm-openhabfloorplan#11]
I dropped the rule into the rules folder and the new rules engine made this code
`
triggers:
  - id: "0"
    configuration:
      groupName: gMagicMirror
    type: core.GroupStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: script
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: >
        // context: majicmirror-1

        val String mirrorUrl = "http://192.168.1.58:8080/openhab"

        var url = mirrorUrl + "?item=" + triggeringItem.name + "&state=" + triggeringItem.state

        sendHttpGetRequest(url)

        logInfo("MagicMirror","Sent to MM: "+ url)
    type: script.ScriptAction
`
But it doesn't work.

**Comment by paphko** [comment]
Please give more info about the issue. What is added to the log files?

**Comment by BenCanada** [comment]
I ended up using `triggeringItemName` instead of `triggeringItem.name`.

**Comment by paphko** [comment]
@BenCanada if your issue is resolved, can we close it?

**Comment by BenCanada** [comment]
Yes, that seemed to do it. The status updates are showing up on the mirror now and no OH3 errors.
