### ISSUE TITLE
Show up, unfortunately does nothing

### ISSUE THREAD

**Issue by masterrich79** [paphko/mmm-openhabfloorplan#13]
Hi there,
maybe a very simple problem: If the floorplan-PNG shows up correctly, but any Number-Information is just the openhab-item name surrounded by brackets:  < >  ... . The lamps don't hide either... So it seems that there is no connection to openhab 2.5.1-2 at all.
Have you some solution-ideas to iterate through..?

![floorplan_doing_nothing](https://user-images.githubusercontent.com/80322929/189458014-1233fdaa-07f9-4111-bf10-7add6788f915.jpeg)

**Thanks** a lot! The Module is great and it would be exaxtly what i was looking for (....)
-Richi

**Comment by paphko** [comment]
Hi. If the item names are shown, you are in configuration mode.
Please read the readme completely.
