### ISSUE TITLE
openhab rule file not work

### ISSUE THREAD

**Issue by supoeric** [paphko/mmm-openhabfloorplan#2]
Hi,
I install the module, and it work fine if I set the "updateInterval:" to one minute. But not work in openhab 2 rules file, 
following is my openhab2 rules content:

var String mirrorUrl = "http://192.168.0.70:8081/openhab"
// whenever one of your items of interest changes, send a GET request to the magic mirror server
rule "RF433_CR to mirror"          	
when
	Item RF433_CR changed 
then
	sendHttpGetRequest(mirrorUrl + "?item=RF433_CR&state=" + RF433_CR.state)
end
rule "RF433_CR_MON1 to mirror"
when
	Item RF433_CR_MON1 changed
then
	sendHttpGetRequest(mirrorUrl + "?item=RF433_CR_MON1&state=" + RF433_CR_MON1.state)
end

My MagicMirror run in server mode and set the port to 8081

Please help.
Thanks
Eric Lin

**Comment by paphko** [comment]
Not enough information. Please provide log output from openhab. And check also logs from mm.

**Comment by BenCanada** [comment]
My rule file is also not working.
Rule setup:
// define your magic mirror URL here; make sure that there is no trailing slash
var String mirrorUrl = "http://192.168.1.45:8080/openhab"

// whenever one of your items of interest changes, send a GET request to the magic mirror server
rule "Light_Garden_Front to mirror"
	when Item Light_Garden_Front changed 
	then sendHttpGetRequest(mirrorUrl + "?item=Light_Garden_Front&state=" + Light_Garden_Front.state)
end
From the openHAB log:
2017-12-29 00:18:03.979 [ERROR] [.smarthome.model.script.actions.HTTP] - Fatal transport error: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused

Any help would be appreciated.
Thanks,
Ben

**Comment by paphko** [comment]
The connection was refused which means that the http request was made but failed to reach the magic mirror module.
Please try to perform the http request manually in a browser to check whether the magic mirror module is reachable and that it is working correctly. Maybe it's a firewall issue, or the port is not working, or ... I don't know...
You may also try the request on the magic mirror, e.g. in the ssh console via curl.

**Comment by BenCanada** [comment]
I found the problem. I had to:

var config = {
	address: "0.0.0.0",
	port: 8080,
	ipWhitelist: [],

in my config,js file to reach the mirror from OpenHab.

**Comment by paphko** [comment]
Thank you for posting the solution :-)
