### ISSUE TITLE
Position does not work

### ISSUE THREAD

**Issue by EugenZimmermann** [paphko/mmm-openhabfloorplan#3]
Hi Paphko,

nice module. I'm new to openHAB and just freshly set everything up on my pi and only changed the lines in your default floorplan. Unfortunately, if I change the position to "top_center" or "top_left" the module ignores other already placed modules and is half way cut because it exceeds the screen at the top. If attached a sample image where I set position to "top_center".

[Sample Image](https://www.dropbox.com/s/afmz2cuqszzg9cf/2017-12-11%2008.57.23.jpg)

Cheers,
Eugen

**Comment by landaisbenj** [comment]
I've this to

![image](https://user-images.githubusercontent.com/32144431/34961685-99a46236-fa40-11e7-9487-aec4504addda.png)

{
		module: 'mmm-openhabfloorplan',
		position: 'top_right', // this can be any of the regions
		config: {

**Comment by paphko** [comment]
This is unfortunate. But I cannot remember that I had to write any code for specific locations. Maybe I missed that?!
At the moment, I don't have time to look into this, but if anyone could figure out how to fix this, I would be happy to merge a pull request :-)

**Comment by landaisbenj** [comment]
Thanks for you re reply.

**Comment by paphko** [comment]
#6 could be a fix for this problem.
I cannot test this atm. Could anyone confirm that the fix is working?

**Comment by landaisbenj** [comment]
Maybe i can try this week end

**Comment by landaisbenj** [comment]
Hello, doesn't work
![image](https://user-images.githubusercontent.com/32144431/38382625-b54a0a64-390a-11e8-94e7-93987493b793.png)

**Comment by landaisbenj** [comment]
Hello WORK FINE !!!

![image](https://user-images.githubusercontent.com/32144431/38382770-18d69ff2-390b-11e8-8673-922c9df1f75a.png)

**Comment by paphko** [comment]
Nice, thanks!
PR merged.
