### ISSUE TITLE
Make an angle for windows or door

### ISSUE THREAD

**Issue by landaisbenj** [paphko/mmm-openhabfloorplan#7]
At the moment, the code only works for right angles because a simple rectangle is drawn:
https://github.com/paphko/mmm-openhabfloorplan/blob/c293c5ad219112affb48547aac076ed358ed7ccf/mmm-openhabfloorplan.js#L205

For wings, it's this function:
https://github.com/paphko/mmm-openhabfloorplan/blob/c293c5ad219112affb48547aac076ed358ed7ccf/mmm-openhabfloorplan.js#L229

It must be good to implement something like this: 
```
transform:rotate(20deg);
-moz-transform: rotate(20deg);
```

**Comment by landaisbenj** [comment]
I must to try this, now i have a little more skill.
[EDIT]:
Maybe do something like this:

> 
> // openhab item: left, top, radius (draws quadrant), midPoint, and optionally counterwindow and color
> 	Reed_Sleeping_right: { left: 12,  top: 231, radius: 30, rotate: 20, midPoint: "top-left" },
> // openhab item: left, top, width, height (draws rectangle), and optionally color
> 	Reed_Sleeping_left:  { left: 90,  top: 301, width: 37, height: 20, rotate: 20 },
> 

By this:
```
// if radius is set, it's a wing with a radius
    if (typeof windowConfig.radius !== 'undefined') {
```
this:
```
    style += "height:" + windowConfig.height + "px;width:" + windowConfig.width + "px;";
```
and this:
```
    -moz-border-radius: 
```

I think we can put this:
```
 // if rotate is set, style will rotate
    if (typeof windowConfig.rotate !== 'undefined') {
        var rotate = windowConfig.rotate;
        style += style + "-moz-transform: rotate(" + windowConfig.rotate + "deg)";
    }
```
In:
https://github.com/paphko/mmm-openhabfloorplan/blob/c293c5ad219112affb48547aac076ed358ed7ccf/mmm-openhabfloorplan.js#L222

I try on my own, and if it's good i pull a merge request.

**Comment by landaisbenj** [comment]
Yeahhhhhh this work very fine !!!!

```
Contact_Chambre2:        { left: 395, top: 100, rotate: 20, radius: 20, midPoint: "bottom-right" },
Contact_Fenetre_Chambre:        { left: 400, top: 20, radius: 25, rotate: 20, midPoint: "top-left", counterwindow: "horizontal" },
```

```
// if rotate is set, style will rotate
if (typeof windowConfig.rotate !== 'undefined') {
    var rotate = windowConfig.rotate;
    style += style + "transform:rotate(" + windowConfig.rotate + "deg);";
}
```


![image](https://user-images.githubusercontent.com/32144431/38385418-1bcb9d32-3912-11e8-8da1-3796becad00b.png)


But i need more time for midpoint lol
I think it double form. But it can do with just one form. I look at this on saturday.

**Comment by paphko** [comment]
This looks great! 
(sorry for writing so late, for some reason I totally missed the notifications from you)

If you got it working properly and you think that it would be worth sharing this with the community, please feel free to add an example to the readme and create a pull request 😃

**Comment by landaisbenj** [comment]
Ah ah. Yes too late. I do another solution. After domoticz I’m on home assistant now. And I do a floor plan by this and make a iframe to push on magic mirror. 

I have never been able to complete this development 😞
