### ISSUE TITLE
change the trigger for windows

### ISSUE THREAD

**Issue by rbrueckner82** [paphko/mmm-openhabfloorplan#9]
Following issue, i have xiaomi door sensors when i open the window the switch changes to ON! At the mirror the window are "closed" when the item switch are ON!

Can i changed the Mirror event that when the Switch ON the Window at the Mirror OPENED and CLOSED when the Switch OFF!?

Thanks!

**Comment by paphko** [comment]
I don't think this is currently possible.
However, you could add an additional virtual switch item in openhab and a new rule that is triggered by the original item which sets the virtual item the reverse value. Use that item for your mirror.
